### ISSUE TITLE
"no case clause matching", when calling to_currency_code/1

### ISSUE THREAD

**Issue by Stroemgren** [elixir-cldr/cldr_territories#47]
I needed a list of all currency codes and wasn't at the time aware of the `ex_cldr_currencies` package, so I took the approach of just getting all known country codes and mapping over `to_currency_code/1`. This led to an error where the map would run for most of the country codes and then break on :CQ, specifically.

It's reproducible with:

```elixir
defmodule Test.Cldr do
  use Cldr,
    locales: [:en],
    default_locale: "en",
    providers: [Cldr.Territory]
end

Test.Cldr.Territory.to_currency_code(:CQ)
```

Stacktrace:
```
** (CaseClauseError) no case clause matching: {:ok, []}
    (ex_cldr_territories 2.9.0) lib/cldr/territory.ex:822: Cldr.Territory.to_currency_code/2
```

I just ran it in isolation on a Livebook with the following deps.
```elixir
Mix.install([
  {:ex_cldr, "~> 2.40"},
  {:ex_cldr_territories, "~> 2.9"},
  {:jason, "~> 1.4"}
])
```

**Comment by Schultzer** [comment]
Thanks, looks like we need to handle the case of territories with no currencies in this case statement https://github.com/elixir-cldr/cldr_territories/blob/f1639c38cba9905d55789052502f606c66c5f95f/lib/cldr/territory.ex#L822.

if you are up for it then a PR is welcomed 🙏

**Comment by Stroemgren** [comment]
I'm up for giving it a go, but I will probably need some direction. At least it depends on the direction.

So either we should return a proper error for this case or we resolve the currency through subdivisions.
Sark Island doesn't have any subdivisions though :)

**Comment by Stroemgren** [comment]
https://github.com/elixir-cldr/cldr_territories/pull/48

This will return `{:ok, nil}` and `nil` for the bang version.

Let me know if you'd rather solve it differently.

**Comment by Schultzer** [comment]
> I'm up for giving it a go, but I will probably need some direction. At least it depends on the direction.
> 
> So either we should return a proper error for this case or we resolve the currency through subdivisions. Sark Island doesn't have any subdivisions though :)

I believe that Sark Island would be under UK, so it might be possible to resolve it by looking up the parent, or maybe the UK subdivision aliases can resolve CQ.

We’re getting the currencies from the info function on https://github.com/elixir-cldr/cldr_territories/blob/f1639c38cba9905d55789052502f606c66c5f95f/lib/cldr/territory.ex#L886

I believe that is where we want to place the logic.

I have not looked at the data available for CQ or the UK so I can’t give you exact instructions.

Regardless, since these things are political and changes over time, then I’m still not sure if we want to error or resolve. @kipcole9 what do you think.

For what is worth, Wikipedia list their currency as GBP https://en.m.wikipedia.org/wiki/Sark

**Comment by kipcole9** [comment]
Not all territories have a known currency. Antartica would be one case. CLDR returns a currency [XXX](https://www.unicode.org/cldr/charts/46/supplemental/detailed_territory_currency_information.html?_gl=1*18tlque*_ga*Nzc2OTQzNzMxLjE3MzIzOTgxOTc.*_ga_BPN1D3SEJM*MTczMjM5ODE5Ni4xLjAuMTczMjM5ODE5Ni4wLjAuMA..) in that case:
```elixir
iex> Cldr.Currency.territory_currencies(:AQ)
{:ok, %{XXX: %{tender: false}}}
```

`XXX` or similar is used in various places in CLDR to denote "Unknown".

In other cases, CLDR doesn't have a currency definition as you observed. In this case `ex_cldr_currencies` returns an error:
```elixir
iex> Cldr.Currency.territory_currencies(:CQ)
{:error, {Cldr.UnknownCurrencyError, "No currencies for :CQ were found"}}
```

I think for consistency purposes, this would be the appropriate thing to do in `ex_cldr_territories`.

BTW, according to [Sark's website](https://sarkgov.co.uk/living-on-sark#:~:text=All%20financial%20services%2Factivity%20on,the%20Guernsey%20Financial%20Services%20Commission.&text=The%20island's%20currency%20is%20the,both%20are%20accepted%20throughout%20Sark.) the currency is the [Guernsy Pound](https://en.wikipedia.org/wiki/Guernsey_pound) - albeit thats a local issue of the GBP.

**Comment by kipcole9** [comment]
And I should probably also return `{:error, {Cldr.UnknownCurrencyError, "No currencies for :__ were found"}}` when CLDR would return `XXX` too, like for the `:AQ` example.

**Comment by Stroemgren** [comment]
Updated the PR.
